# Generated by Django 4.0.10 on 2024-01-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=200, verbose_name='название номер контракта')),
                ('contract_sum', models.PositiveIntegerField(default='0', verbose_name='сумма контракта')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=200, verbose_name='название номер контракта')),
                ('contract_sum', models.PositiveIntegerField(default='0', verbose_name='сумма контракта')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала действия')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент')),
            ],
        ),
    ]
