# Generated by Django 4.0.10 on 2024-01-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.service', verbose_name='Конкретная услуга клиента'),
        ),
        migrations.AddField(
            model_name='additionalcontract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='additionalcontract',
            name='main_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.contract', verbose_name='главный контракт'),
        ),
        migrations.AddField(
            model_name='additionalcontract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.service', verbose_name='Конкретная услуга клиента'),
        ),
    ]
