# Generated by Django 4.0.10 on 2024-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcontract',
            name='diff_sum',
            field=models.PositiveIntegerField(default='0', verbose_name='сумма контракта'),
        ),
    ]
