# Generated by Django 4.0.10 on 2024-01-30 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_remove_servicesmonthlybill_adv_all_sum_and_more'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcontract',
            name='adv_all_sum',
            field=models.PositiveIntegerField(default='0', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='additionalcontract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.service', verbose_name='Конкретная услуга клиента'),
        ),
    ]
