# Generated by Django 4.0.10 on 2024-01-19 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contract',
        ),
        migrations.AddField(
            model_name='contract',
            name='сlient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
