# Generated by Django 4.0.10 on 2024-01-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_remove_client_contract_contract_сlient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='сlient',
            new_name='client',
        ),
        migrations.AddField(
            model_name='contract',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
