# Generated by Django 4.0.10 on 2024-01-22 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_serviceclient_contract'),
        ('client', '0008_rename_сlient_contract_client_contract_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.serviceclient'),
        ),
    ]
