# Generated by Django 4.0.10 on 2024-01-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_contract_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bank',
            field=models.CharField(choices=[('OOO', 'ООО'), ('IP', 'ИП'), ('$', '$'), ('NONE', '---')], default='NONE', max_length=4),
        ),
    ]
