# Generated by Django 4.0.10 on 2024-01-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MetaCategoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NameOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OperationOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('sum', models.PositiveIntegerField(default='0')),
                ('bank', models.CharField(choices=[('OOO', 'ООО'), ('IP', 'ИП'), ('$', '$')], default='OOO', max_length=4, verbose_name='Счет поступления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.categoryoperation', verbose_name='Категория операции')),
                ('meta_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.metacategoryoperation', verbose_name='Главная категория операции')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.nameoperation', verbose_name='Название операции')),
            ],
        ),
        migrations.CreateModel(
            name='OperationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('sum', models.PositiveIntegerField(default='0')),
                ('bank', models.CharField(choices=[('OOO', 'ООО'), ('IP', 'ИП'), ('$', '$')], default='OOO', max_length=4)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.categoryoperation')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.nameoperation')),
            ],
        ),
    ]
