# Generated by Django 4.0.10 on 2024-02-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationentry',
            old_name='sum',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='operationentry',
            name='bank',
        ),
    ]
