# Generated by Django 4.0.10 on 2024-01-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationentry',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='operationout',
            name='bank',
        ),
    ]
