# Generated by Django 4.0.10 on 2024-01-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_operationentry_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
