# Generated by Django 4.0.10 on 2024-02-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_operationentry_monthlybill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationentry',
            old_name='monthlyBill',
            new_name='monthly_bill',
        ),
    ]
