# Generated by Django 4.0.10 on 2024-02-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_rename_monthlybill_operationentry_monthly_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationentry',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.bankoperation'),
        ),
        migrations.AlterField(
            model_name='operationentry',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.nameoperation'),
        ),
    ]
