# Generated by Django 4.0.10 on 2024-02-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_servicesmonthlybill_check_entry_and_more'),
        ('operation', '0006_alter_operationentry_bank_alter_operationentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationout',
            name='suborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.subcontractmonth', verbose_name='Субподряд'),
        ),
        migrations.AlterField(
            model_name='operationout',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.bankoperation'),
        ),
    ]
