# Generated by Django 4.0.10 on 2024-03-01 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
