# Generated by Django 4.0.10 on 2024-03-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_operation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='data',
            field=models.DateField(verbose_name='Дата добавления вручную'),
        ),
    ]
