# Generated by Django 4.0.10 on 2024-04-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_subcontractmonth_created_timestamp'),
        ('operation', '0010_alter_operation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('amount', models.PositiveIntegerField(default='0', verbose_name='сумма оплаты по оперсчету')),
            ],
        ),
        migrations.CreateModel(
            name='OperAccountsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='название типа расхода по оперсчету')),
            ],
        ),
        migrations.AddField(
            model_name='bankoperation',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.bankoperation', verbose_name='банк конечный назначения операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='monthly_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.servicesmonthlybill', verbose_name='месячный счет для приходов и оплат'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='suborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.subcontractmonth', verbose_name='Субподряд для оплат'),
        ),
    ]
