# Generated by Django 4.0.10 on 2024-04-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_operaccounts_operaccountsname_bankoperation_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankoperation',
            old_name='slug',
            new_name='slugish',
        ),
    ]
