# Generated by Django 4.0.10 on 2024-04-03 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_rename_slug_bankoperation_slugish'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaccountsname',
            name='meta_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.metacategoryoperation', verbose_name='Главная категория операции'),
        ),
        migrations.CreateModel(
            name='OperAccountsNameSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='название типа субкатегории расхода по оперсчету')),
                ('oper_accounts_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.operaccountsname', verbose_name='название типа расхода по оперсчету')),
            ],
        ),
    ]
