# Generated by Django 4.0.10 on 2024-04-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_operaccountsname_meta_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoperation',
            name='meta_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.metacategoryoperation', verbose_name='общая категория'),
        ),
    ]
