# Generated by Django 4.0.10 on 2024-04-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_categoryoperation_meta_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationout',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='operationout',
            name='category',
        ),
        migrations.RemoveField(
            model_name='operationout',
            name='meta_category',
        ),
        migrations.RemoveField(
            model_name='operationout',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operationout',
            name='suborder',
        ),
        migrations.AddField(
            model_name='operation',
            name='meta_categ',
            field=models.CharField(choices=[('oper_account', 'oper_account'), ('banking', 'banking'), ('nalog', 'nalog'), ('salary', 'salary'), ('suborders', 'suborders'), ('entrering', 'entrering'), ('none', 'none')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='OperationEntry',
        ),
        migrations.DeleteModel(
            name='OperationOut',
        ),
    ]
