# Generated by Django 4.0.10 on 2024-04-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_subcatcategoryoperation_subcategoryoperation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubcatCategoryOperation',
        ),
    ]
