# Generated by Django 4.0.10 on 2024-04-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_delete_subcatcategoryoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoperation',
            name='sub_categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.subcategoryoperation', verbose_name='Доп Категория операции'),
        ),
    ]
