# Generated by Django 4.0.10 on 2024-04-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_categoryoperation_sub_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoperation',
            name='meta_categ',
            field=models.CharField(choices=[('oper_account', 'oper_account'), ('banking', 'banking'), ('nalog', 'nalog'), ('salary', 'salary'), ('suborders', 'suborders'), ('entrering', 'entrering'), ('none', 'none')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='categoryoperation',
            name='test',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
