# Generated by Django 4.0.10 on 2024-04-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0021_remove_categoryoperation_meta_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoperation',
            name='meta_category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.metacategoryoperation', verbose_name='общая категория'),
        ),
        migrations.AddField(
            model_name='categoryoperation',
            name='tes5',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
