# Generated by Django 4.0.10 on 2024-04-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_categoryoperation_meta_category1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoperation',
            name='meta_category1',
        ),
        migrations.AddField(
            model_name='categoryoperation',
            name='tes4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.metacategoryoperation', verbose_name='общая категория'),
        )
    ]
