# Generated by Django 4.0.10 on 2024-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_remove_categoryoperation_meta_category1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoperation',
            name='tes6',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
