# Generated by Django 4.0.10 on 2024-04-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0024_categoryoperation_tes6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoperation',
            name='tes4',
        ),
    ]
