# Generated by Django 4.0.10 on 2024-04-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0025_remove_categoryoperation_tes4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoperation',
            name='tes2',
        ),
        migrations.RemoveField(
            model_name='categoryoperation',
            name='tes3',
        ),
        migrations.RemoveField(
            model_name='categoryoperation',
            name='tes5',
        ),
        migrations.RemoveField(
            model_name='categoryoperation',
            name='tes6',
        ),
        migrations.RemoveField(
            model_name='categoryoperation',
            name='test',
        ),
    ]
