# Generated by Django 4.0.10 on 2024-04-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0026_remove_categoryoperation_tes2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryoperation',
            name='meta_categ',
            field=models.CharField(choices=[('oper_account', 'oper_account'), ('banking', 'banking'), ('nalog', 'nalog'), ('salary', 'salary'), ('suborders', 'suborders'), ('entrering', 'entrering'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
