# Generated by Django 4.0.10 on 2024-04-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0027_subcategoryoperation_meta_categ'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='subcategoryoperation',
        #     name='meta_category',
        #     field=models.CharField(choices=[('oper_account', 'oper_account'), ('banking', 'banking'), ('nalog', 'nalog'), ('salary', 'salary'), ('suborders', 'suborders'), ('entrering', 'entrering'), ('none', 'none')], default='none', max_length=20),
        # ),
        migrations.RenameField(
            model_name='subcategoryoperation',
            old_name='meta_categ',
            new_name='meta_category',
        ),
        migrations.AddField(
            model_name='subcategoryoperation',
            name='meta_categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.metacategoryoperation', verbose_name='Доп Категория операции'),
        ),
        
        # migrations.AlterField(
        #     model_name='subcategoryoperation',
        #     name='meta_categ',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.metacategoryoperation', verbose_name='Доп Категория операции'),
        # ),
    ]
