# Generated by Django 4.0.10 on 2024-04-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0028_subcategoryoperation_meta_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryoperation',
            name='name2',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
