# Generated by Django 4.0.10 on 2024-04-24 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0029_subcategoryoperation_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='created_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
