# Generated by Django 4.0.10 on 2024-04-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_alter_operation_created_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryoperation',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operation.bankoperation', verbose_name='банк конечный назначения операции'),
        ),
    ]
