# Generated by Django 4.0.10 on 2024-04-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_date_end_employee_date_start'),
        ('operation', '0031_subcategoryoperation_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='зарплата'),
        ),
    ]
