# Generated by Django 4.0.10 on 2025-04-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0032_operation_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='bank_first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_first', to='operation.bankoperation', verbose_name='банк начальный отправки операции'),
        ),
    ]
