# Generated by Django 4.0.10 on 2024-01-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(choices=[('ADV', 'ADV'), ('SEO', 'SEO'), ('SUP', 'SUP'), ('DEV', 'DEV'), ('SMM', 'SMM'), ('NONE', 'NONE')], default='NONE', max_length=4)),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('NONE', 'NONE')], default='NONE', max_length=4)),
                ('contract_sum', models.PositiveIntegerField(default='0')),
                ('account', models.CharField(choices=[('1', 'OOO'), ('2', 'ИП'), ('2', 'Нал'), ('NONE', 'NONE')], default='NONE', max_length=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
