# Generated by Django 4.0.10 on 2024-01-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('operation', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='название площадки')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(choices=[('ADV', 'ADV'), ('SEO', 'SEO'), ('SUP', 'SUP'), ('DEV', 'DEV'), ('SMM', 'SMM'), ('NONE', '---')], default='NONE', max_length=4)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='название субподряда')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('amount', models.PositiveIntegerField(default='0', verbose_name='сумма субподряд')),
                ('percent', models.PositiveIntegerField(default='0', verbose_name='процент для исполнителя')),
                ('adv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.adv', verbose_name='Рекламная площадка')),
                ('check_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.operationout', verbose_name='Проверка оплаты')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.subcontractother', verbose_name='Рекламная площадка')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesMonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_all_sum', models.PositiveIntegerField(default='0', verbose_name='')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('additional_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.additionalcontract')),
                ('check_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.operationentry', verbose_name='Проверка оплаты')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.contract')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.serviceclient')),
                ('subcontract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.subcontractmonth')),
            ],
        ),
    ]
