# Generated by Django 4.0.10 on 2024-01-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Категории услуг')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicesmonthlybill',
            name='adv_all_sum',
        ),
        migrations.RemoveField(
            model_name='servicesmonthlybill',
            name='check_entry',
        ),
        migrations.RemoveField(
            model_name='servicesmonthlybill',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='subcontractmonth',
            name='other',
        ),
    ]
