# Generated by Django 4.0.10 on 2024-02-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_subcontractmonth_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmonthlybill',
            name='check_entry',
        ),
        migrations.RemoveField(
            model_name='subcontractmonth',
            name='check_entry',
        ),
    ]
