# Generated by Django 4.0.10 on 2024-01-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceclient_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceclient',
            name='account',
        ),
        migrations.RemoveField(
            model_name='serviceclient',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='serviceclient',
            name='contract_sum',
        ),
        migrations.RemoveField(
            model_name='serviceclient',
            name='month',
        ),
    ]
