# Generated by Django 4.0.10 on 2024-01-22 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_serviceclient_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='created_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
