# Generated by Django 4.0.10 on 2024-02-26 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicesmonthlybill_adv_all_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmonthlybill',
            name='adv_all_sum',
            field=models.PositiveIntegerField(default=None, verbose_name='сумма ведения для адв'),
        ),
        migrations.AlterField(
            model_name='servicesmonthlybill',
            name='chekin_add_subcontr',
            field=models.BooleanField(default=False, verbose_name='чекин есть ли распределение денег по субподрядам'),
        ),
        migrations.AlterField(
            model_name='servicesmonthlybill',
            name='chekin_sum_adv',
            field=models.BooleanField(default=False, verbose_name='чекин оплаты всех субподрядов'),
        ),
        migrations.AlterField(
            model_name='servicesmonthlybill',
            name='chekin_sum_entrees',
            field=models.BooleanField(default=False, verbose_name='чекин получения полной оплаты от клиента'),
        ),
        migrations.AlterField(
            model_name='servicesmonthlybill',
            name='diff_sum',
            field=models.PositiveIntegerField(default='0', verbose_name='сумма для распределения по скбподряду адв'),
        ),
        migrations.AlterField(
            model_name='subcontractmonth',
            name='month_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicesmonthlybill'),
        ),
    ]
