# Generated by Django 4.0.10 on 2024-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviceclient_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceclient',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
