# Generated by Django 4.0.10 on 2024-01-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_serviceclient_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceclient',
            name='contract',
        ),
    ]
