# Generated by Django 4.0.10 on 2024-03-01 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_servicesmonthlybill_adv_all_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmonthlybill',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
