# Generated by Django 4.0.10 on 2024-01-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_serviceclient_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='account',
            field=models.CharField(choices=[('1', 'OOO'), ('2', 'ИП'), ('2', 'Нал'), ('NONE', 'NONE')], default='NONE', max_length=4),
        ),
        migrations.CreateModel(
            name='SubcontractAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seosub_people', models.CharField(blank=True, max_length=200, null=True)),
                ('seosub_sum', models.PositiveIntegerField(default='0')),
                ('seosub_people_other', models.CharField(blank=True, max_length=200, null=True)),
                ('seosub_sum_other', models.PositiveIntegerField(default='0')),
                ('drvsub_people', models.CharField(blank=True, max_length=200, null=True)),
                ('drvsub_sum', models.PositiveIntegerField(default='0')),
                ('designersub_people', models.CharField(blank=True, max_length=200, null=True)),
                ('designersub_sum', models.PositiveIntegerField(default='0')),
                ('adv_all_sum', models.PositiveIntegerField(default='0')),
                ('service_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.serviceclient')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractADV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_name', models.CharField(choices=[('YANDEX', 'Яндекс Директ'), ('MAIL', 'Таргет Mail.ru/VK'), ('GOOGLE', 'Google Adwords'), ('OTHER', 'ДРУГОЕ'), ('NONE', '---')], default='NONE', max_length=10)),
                ('adv_sum', models.PositiveIntegerField(default='0')),
                ('service_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.serviceclient')),
            ],
        ),
    ]
