# Generated by Django 4.0.10 on 2024-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicesmonthlybill_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmonthlybill',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления вручную'),
        ),
    ]
