# Generated by Django 4.0.10 on 2024-03-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_servicesmonthlybill_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmonthlybill',
            name='data',
        ),
    ]
