# Generated by Django 4.0.10 on 2024-01-22 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_serviceclient_account_subcontractall_subcontractadv'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractadv',
            name='created_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subcontractall',
            name='created_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
