# Generated by Django 4.0.10 on 2024-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_remove_servicesmonthlybill_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmonthlybill',
            name='created_timestamp',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
