# Generated by Django 4.0.10 on 2024-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_subcontractadv_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractadv',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='subcontractall',
            name='created_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
