# Generated by Django 4.0.10 on 2024-03-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_servicesmonthlybill_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractmonth',
            name='created_timestamp',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
