# Generated by Django 4.0.10 on 2024-01-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_subcontractadv_created_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractall',
            name='adv_all_sum',
        ),
        migrations.AddField(
            model_name='serviceclient',
            name='adv_all_sum',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
