# Generated by Django 4.0.10 on 2024-04-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_subcontractmonth_created_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmonthlybill',
            name='additional_contract',
        ),
    ]
