version: '3.7'
services:

  web:
    build: ./python/
    command: python ./lemurproj/manage.py runserver 0.0.0.0:3000
    volumes:
      - ../:/home/sites/lemurproj/
    ports:
      - 3000:3000
    # env_file:
    #   - ./.env

  celery:
    container_name: celery
    build: ./python/
    command: >
      sh -c "cd lemurproj/ && celery -A project worker -l info"
    volumes:
      - ../:/home/sites/lemurproj/
    ports:
      - "5566:5566"
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    build: ./python/
    command: >
      sh -c "cd lemurproj/ && celery -A project beat -l info"
    volumes:
      - ../:/home/sites/lemurproj/
    depends_on:
      - redis
      - celery

  redis:
    container_name: redis
    image: redis
    ports:
        - "6379:6379"    

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 89:8080
    # db:
    # image: mysql:5.7
    # ports:
    #   - '3306:3306'
    # environment:
    #   MYSQL_DATABASE: ''dyugaev_anast'
    #   MYSQL_USER: ''dyugaev_anast'
    #   MYSQL_PASSWORD: 'PRgD0%1V'
    #   MYSQL_ROOT_PASSWORD: 'PRgD0%1V'
    # restart: always
    # volumes:
    #   - ./db_django:/var/lib/mysql
    # version: '3.9'

    # services:
    #   python:
    #     container_name: python
    #     restart: always
    #     build: ./python/
    #     command: python ./${PROJECT}/manage.py runserver 0.0.0.0:8000
    #     volumes:
    #       - ../:/home/sites/${PROJECT}/
    #     env_file:
    #       - .env
    #     ports:
    #       - "8000:8000"

    #   # celery:
    #   #   container_name: celery
    #   #   build: ./python/
    #   #   command: >
    #   #     sh -c "cd ${PROJECT}/ && celery -A project worker -l info"
    #   #   volumes:
    #   #     - ../:/home/sites/${PROJECT}/
    #   #   env_file:
    #   #     - ./.env
    #   #   ports:
    #   #     - "5566:5566"
    #   #   depends_on:
    #   #     - redis

    #   # celery-beat:
    #   #   container_name: celery-beat
    #   #   build: ./python/
    #   #   command: >
    #   #     sh -c "cd ${PROJECT}/ && celery -A project beat -l info"
    #   #   volumes:
    #   #     - ../:/home/sites/${PROJECT}/
    #   #   depends_on:
    #   #     - redis
    #   #     - celery

    #   # dashboard:
    #   #   container_name: flower
    #   #   build: ./python/
    #   #   command: celery flower --port=5555
    #   #   ports:
    #   #     - 5555:5555
    #   #   environment:
    #   #     - DEBUG=1
    #   #     # - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m 
    #   #     - SECRET_KEY=django-insecure-5c@y9xy*-pk7vr!rz^q^qfaj0_k2-21zjtplcs=^&ju8@z(a+=
    #   #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    #   #     - CELERY_BROKER=redis://redis:6379/0
    #   #     - CELERY_BACKEND=redis://redis:6379/0
    #   #   depends_on:
    #   #     - python
    #   #     - redis
    #   #     - celery

    #   # redis:
    #   #   container_name: redis
    #   #   image: redis
    #   #   ports:
    #   #     - "6379:6379"

    #   # adminer:
    #   #   container_name: adminer
    #   #   image: adminer
    #   #   restart: always
    #   #   ports:
    #   #     - 89:8080
