# Generated by Django 4.0.10 on 2024-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('INTERNAL', 'Внешний'), ('EXTERNAL', 'Внутренний')], default='EXTERNAL', max_length=8)),
            ],
        ),
    ]
