# Generated by Django 4.0.10 on 2024-04-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия'),
        ),
    ]
