# Generated by Django 4.0.10 on 2024-01-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(choices=[('OOO', 'ООО'), ('IP', 'ИП'), ('$', '$'), ('NONE', '---')], default='NONE', max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
