# Generated by Django 4.0.10 on 2024-01-24 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_remove_operationentry_bank_remove_operationout_bank'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OOO', 'ООО'), ('IP', 'ИП'), ('$', '$'), ('NONE', '---')], default='NONE', max_length=4)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.operationentry')),
                ('operation_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.operationout')),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
